# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test-project:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6,3.7,3.8,3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest


  build-project:
    name: build sego-cli and upload to artifacts
    runs-on: ubuntu-latest
    needs: test-project
    strategy:
      matrix:
        python-version: [ 3.6,3.7,3.8,3.9 ]
    steps:
      - name: create repository path
        run: |
          mkdir sego

      - uses: actions/checkout@v2
        with:
           path: sego/

      - name: Install dependencies
        working-directory: sego
        run: |
          pip install -r requirements.txt --target . --upgrade


      - name: Generate zip folder
        run: |
          python -m zipapp sego/

      - name: Use the upload artifact github action
        uses: actions/upload-artifact@v2
        with:
          name: sego
          path: sego.pyz

  release-project:
    name: release sego-cli to github releases
    runs-on: ubuntu-latest
    needs: build-project
    strategy:
        matrix:
          python-version: [ 3.9]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: sego

     - name: Adding python shebang
       run: |
         echo '#!/usr/bin/env python' | cat - sego.pyz > sego
         chmod 775 sego 


      - name: Create release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: v${{github.run_number}}
          release_name: Release v${{github.run_number}}

      - name: Upload file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create-new-release.outputs.upload_url}}
          asset_path: sego
          asset_name: sego
          asset_content_type: application/zip






